INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (1, N'Afghanistan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (2, N'Albania')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (3, N'Algeria')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (4, N'America')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (5, N'Andorra')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (6, N'Angola')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (7, N'Antigua')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (8, N'Argentina')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (9, N'Armenia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (10, N'Australia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (11, N'Austria')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (12, N'Azerbaijan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (13, N'Bahamas')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (14, N'Bahrain')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (15, N'Bangladesh')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (16, N'Barbados')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (17, N'Belarus')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (18, N'Belgium')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (19, N'Belize')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (20, N'Benin')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (21, N'Bhutan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (22, N'Bissau')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (23, N'Bolivia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (24, N'Bosnia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (25, N'Botswana')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (26, N'Brazil')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (27, N'British')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (28, N'Brunei')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (29, N'Bulgaria')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (30, N'Burkina')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (31, N'Burma')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (32, N'Burundi')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (33, N'Cambodia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (34, N'Cameroon')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (35, N'Canada')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (36, N'Cape Verde')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (37, N'Central African Republic')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (38, N'Chad')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (39, N'Chile')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (40, N'China')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (41, N'Colombia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (42, N'Comoros')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (43, N'Congo')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (44, N'Costa Rica')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (45, N'country debt')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (46, N'Croatia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (47, N'Cuba')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (48, N'Cyprus')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (49, N'Czech')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (50, N'Denmark')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (51, N'Djibouti')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (52, N'Dominica')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (53, N'East Timor')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (54, N'Ecuador')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (55, N'Egypt')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (56, N'El Salvador')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (57, N'Emirate')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (58, N'England')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (59, N'Eritrea')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (60, N'Estonia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (61, N'Ethiopia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (62, N'Fiji')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (63, N'Finland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (64, N'France')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (65, N'Gabon')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (66, N'Gambia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (67, N'Georgia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (68, N'Germany')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (69, N'Ghana')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (70, N'Great Britain')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (71, N'Greece')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (72, N'Grenada')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (73, N'Grenadines')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (74, N'Guatemala')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (75, N'Guinea')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (76, N'Guyana')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (77, N'Haiti')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (78, N'Herzegovina')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (79, N'Honduras')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (80, N'Hungary')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (81, N'Iceland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (82, N'in usa')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (83, N'India')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (84, N'Indonesia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (85, N'Iran')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (86, N'Iraq')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (87, N'Ireland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (88, N'Israel')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (89, N'Italy')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (90, N'Ivory Coast')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (91, N'Jamaica')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (92, N'Japan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (93, N'Jordan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (94, N'Kazakhstan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (95, N'Kenya')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (96, N'Kiribati')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (97, N'Korea')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (98, N'Kosovo')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (99, N'Kuwait')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (100, N'Kyrgyzstan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (101, N'Laos')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (102, N'Latvia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (103, N'Lebanon')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (104, N'Lesotho')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (105, N'Liberia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (106, N'Libya')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (107, N'Liechtenstein')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (108, N'Lithuania')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (109, N'Luxembourg')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (110, N'Macedonia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (111, N'Madagascar')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (112, N'Malawi')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (113, N'Malaysia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (114, N'Maldives')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (115, N'Mali')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (116, N'Malta')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (117, N'Marshall')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (118, N'Mauritania')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (119, N'Mauritius')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (120, N'Mexico')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (121, N'Micronesia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (122, N'Moldova')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (123, N'Monaco')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (124, N'Mongolia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (125, N'Montenegro')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (126, N'Morocco')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (127, N'Mozambique')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (128, N'Myanmar')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (129, N'Namibia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (130, N'Nauru')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (131, N'Nepal')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (132, N'Netherlands')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (133, N'New Zealand')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (134, N'Nicaragua')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (135, N'Niger')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (136, N'Nigeria')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (137, N'Norway')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (138, N'Oman')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (139, N'Pakistan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (140, N'Palau')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (141, N'Panama')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (142, N'Papua')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (143, N'Paraguay')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (144, N'Peru')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (145, N'Philippines')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (146, N'Poland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (147, N'Portugal')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (148, N'Qatar')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (149, N'Romania')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (150, N'Russia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (151, N'Rwanda')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (152, N'Samoa')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (153, N'San Marino')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (154, N'Sao Tome')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (155, N'Saudi Arabia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (156, N'scotland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (157, N'scottish')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (158, N'Senegal')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (159, N'Serbia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (160, N'Seychelles')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (161, N'Sierra Leone')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (162, N'Singapore')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (163, N'Slovakia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (164, N'Slovenia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (165, N'Solomon')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (166, N'Somalia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (167, N'South Africa')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (168, N'South Sudan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (169, N'Spain')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (170, N'Sri Lanka')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (171, N'St. Kitts')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (172, N'St. Lucia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (173, N'St Kitts')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (174, N'St Lucia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (175, N'Saint Kitts')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (176, N'Santa Lucia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (177, N'Sudan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (178, N'Suriname')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (179, N'Swaziland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (180, N'Sweden')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (181, N'Switzerland')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (182, N'Syria')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (183, N'Taiwan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (184, N'Tajikistan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (185, N'Tanzania')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (186, N'Thailand')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (187, N'Tobago')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (188, N'Togo')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (189, N'Tonga')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (190, N'Trinidad')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (191, N'Tunisia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (192, N'Turkey')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (193, N'Turkmenistan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (194, N'Tuvalu')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (195, N'Uganda')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (196, N'Ukraine')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (197, N'United Kingdom')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (198, N'United States')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (199, N'Uruguay')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (200, N'USA')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (201, N'Uzbekistan')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (202, N'Vanuatu')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (203, N'Vatican')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (204, N'Venezuela')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (205, N'Vietnam')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (206, N'wales')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (207, N'welsh')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (208, N'Yemen')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (209, N'Zambia')
INSERT INTO [dbo].[CountryList] ([CountryID], [CountryName]) VALUES (210, N'Zimbabwe')
